baseURL: "https://haileyschoelkopf.github.io" 
title: Hailey Schoelkopf
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Blog
          url: blog/
          weight: 1
        - name: Books
          url: books/
          weight: 2 
        - name: Papers
          url: papers/
          weight: 3
        # - name: Courses
        #   url: courses/
        #   weight: 4

params:
    description: "TODO"
    author: Hailey Schoelkopf
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hailey Schoelkopf
          subtitle: "Coming soon. Under construction"
          imageUrl: ""
          imageWidth: 160
          imageHeight: 160
          imageTitle: Hailey Schoelkopf
          buttons:
            - name: Blog
              url: blog/
            - name: Research
              url: papers/
            - name: About
              url: about/
            # - name: Courses
            #   url: courses/
            - name: Tags
              url: tags/
            # - name: Archive
            #   url: archive/

    socialIcons:
        - name: Email
          url: mailto:hailey.ruth.schoelkopf@gmail.com
        - name: CV
          url: todo.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=XLahYIYAAAAJ
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: GitHub
          url: https://github.com/haileyschoelkopf
        # - name: YouTube
        #   url: 
        - name: Twitter
          url: https://twitter.com/haileysch__

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hailey Schoelkopf"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
